version: '3'

services: 
  api:
    build: ./api
    volumes:
      - /app/node_modules
      - ./api:/app
  client:
    image: php:apache
    volumes: 
      - ./client:/var/www/html
    ports:
      - 5001:80
    depends_on:
      - api